export type DailyImpulseAudience = "management" | "sales" | "employee";
export type DailyImpulsePeriod = "morning" | "afternoon";

export const dashboardDailyImpulses: Record<DailyImpulseAudience, Record<DailyImpulsePeriod, string[]>> = {
  "management": {
    "morning": [
      "Erst Überblick, dann Entscheidung.",
      "Prioritäten bestimmen den Takt.",
      "Der Tag beginnt mit den Engpässen.",
      "Was heute zählt, braucht klare Verantwortung.",
      "Risiken früh sehen, statt spät reagieren.",
      "Klarheit im Kalender schafft Klarheit im Unternehmen.",
      "Entscheidungen brauchen Daten, nicht Annahmen.",
      "Ziele zuerst, Maßnahmen danach.",
      "Der erste Blick gilt den kritischen Punkten.",
      "Führung beginnt mit eindeutigen Erwartungen.",
      "Was wichtig ist, darf nicht warten.",
      "Gute Steuerung beginnt mit wenigen Kennzahlen.",
      "Ein klarer Fokus verhindert Nebenkriegsschauplätze.",
      "Verantwortlichkeiten prüfen, bevor Aufgaben starten.",
      "Strategische Themen brauchen festen Raum.",
      "Wer Prioritäten nicht setzt, bekommt sie gesetzt.",
      "Früh abstimmen, bevor Aufwand entsteht.",
      "Entscheidungen ohne Kontext schaffen neue Fragen.",
      "Ein kurzer Überblick spart lange Schleifen.",
      "Der Engpass zeigt die nächste Aufgabe.",
      "Besser eine klare Entscheidung als drei offene Optionen.",
      "Tagesziele müssen messbar bleiben.",
      "Erwartungen aussprechen, bevor Ergebnisse fehlen.",
      "Kontrolle ersetzt keine klare Vereinbarung.",
      "Zahlen zeigen Wirkung, nicht Absicht.",
      "Wer steuert, muss sichtbar machen, worauf es ankommt.",
      "Offene Risiken gehören auf die Agenda.",
      "Ein voller Kalender ist noch keine Priorität.",
      "Entscheidungen werden besser, wenn Rollen klar sind.",
      "Heute klären, was morgen blockieren könnte.",
      "Führung braucht Überblick, nicht Dauerreaktion.",
      "Wichtiges zuerst, Dringendes danach einordnen.",
      "Ein guter Tag beginnt mit klaren Entscheidungswegen.",
      "Was nicht gemessen wird, bleibt schwer steuerbar.",
      "Früh fokussieren, später weniger korrigieren.",
      "Die wichtigste Frage lautet: Was fehlt zur Entscheidung?",
      "Verantwortung beginnt bei klarer Zuordnung.",
      "Gute Führung reduziert Unklarheit.",
      "Planung muss Spielraum und Grenzen zeigen.",
      "Wer Klarheit schafft, beschleunigt andere.",
      "Der Tag braucht Richtung, bevor Tempo entsteht.",
      "Reibung früh erkennen, bevor sie teuer wird.",
      "Entscheidungen brauchen Fristen, sonst werden sie Themen.",
      "Ein klarer Auftrag spart Abstimmungsaufwand.",
      "Heute zählt, was Wirkung erzeugt.",
      "Führung heißt, Prioritäten sichtbar zu halten.",
      "Strategische Arbeit braucht geschützte Zeit.",
      "Offene Zuständigkeiten kosten Geschwindigkeit.",
      "Ein sauberer Start verhindert unnötige Eskalation.",
      "Klarheit am Morgen zahlt auf den ganzen Tag ein."
    ],
    "afternoon": [
      "Offene Entscheidungen heute noch einordnen.",
      "Was nicht entschieden ist, bleibt ein Risiko.",
      "Der Nachmittag zeigt, was wirklich vorankommt.",
      "Zwischenstände sind Führungsinstrumente.",
      "Offene Punkte brauchen Eigentümer und Frist.",
      "Was heute offen bleibt, muss bewusst offen bleiben.",
      "Steuerung endet nicht mit dem Meeting.",
      "Ergebnisse zählen erst, wenn sie nachvollziehbar sind.",
      "Nachhalten ist Teil der Verantwortung.",
      "Ein kurzer Status verhindert späte Überraschungen.",
      "Entscheidungen dokumentieren, bevor sie verwässern.",
      "Der Abschluss des Tages beginnt vor Feierabend.",
      "Offene Risiken gehören nicht in den nächsten Morgen.",
      "Was erledigt ist, braucht klare Ablage.",
      "Verantwortung endet nicht bei der Delegation.",
      "Gute Führung prüft Wirkung, nicht nur Aktivität.",
      "Nachmittags zählt, was noch geklärt werden muss.",
      "Ein offener Punkt ohne Frist bleibt ein offener Punkt.",
      "Heute nachhalten, morgen schneller starten.",
      "Ergebnisse brauchen Sichtbarkeit.",
      "Unklare Entscheidungen werden zu Rückfragen.",
      "Der Tagesabschluss zeigt die Qualität der Steuerung.",
      "Was nicht dokumentiert ist, bleibt interpretierbar.",
      "Kritische Themen nicht in den nächsten Tag schieben.",
      "Führung heißt auch, Abschlussklarheit zu schaffen.",
      "Ein sauberer Status spart das nächste Meeting.",
      "Offene Themen brauchen Priorität, nicht nur Notiz.",
      "Der Nachmittag gehört der Klärung.",
      "Nacharbeit entscheidet über Verlässlichkeit.",
      "Ergebnisse müssen anschlussfähig sein.",
      "Was entschieden wurde, muss auffindbar bleiben.",
      "Gute Steuerung erkennt Abweichungen rechtzeitig.",
      "Ein klarer Abschluss stärkt den nächsten Start.",
      "Nicht jedes Thema braucht ein Meeting, aber jedes Thema braucht Klärung.",
      "Fristen prüfen, bevor sie reißen.",
      "Wo Verantwortung fehlt, entsteht Verzögerung.",
      "Nachhalten schützt vor Wiederholungsfehlern.",
      "Der letzte Blick gilt den offenen Abhängigkeiten.",
      "Entscheiden heißt auch, Folgeaufgaben zu klären.",
      "Sichtbare Ergebnisse schaffen Verbindlichkeit.",
      "Was heute geklärt ist, blockiert morgen nicht.",
      "Führung braucht am Nachmittag Konsequenz.",
      "Der Tagesstand muss zur Planung passen.",
      "Abweichungen früh benennen, statt später erklären.",
      "Gute Entscheidungen brauchen saubere Übergabe.",
      "Ein Punkt ist erst erledigt, wenn der nächste Schritt klar ist.",
      "Tagesabschluss ist kein Formalismus.",
      "Was offen bleibt, braucht eine bewusste Entscheidung.",
      "Verbindlichkeit entsteht durch Nachhalten.",
      "Der nächste Tag beginnt mit dem heutigen Abschluss."
    ]
  },
  "sales": {
    "morning": [
      "Gute Gespräche beginnen mit guter Vorbereitung.",
      "Der erste Blick gilt den wichtigsten Kunden.",
      "Chancen brauchen Struktur, nicht Zufall.",
      "Vorbereitung entscheidet über Gesprächsqualität.",
      "Wer den Bedarf versteht, verkauft gezielter.",
      "Der Tag beginnt mit klaren Kundenzielen.",
      "Angebote brauchen Kontext, nicht nur Preise.",
      "Aktivität wirkt besser mit Priorität.",
      "Erst Pipeline prüfen, dann loslegen.",
      "Kundenkontakt braucht Anlass und Ziel.",
      "Gute Fragen schaffen bessere Gespräche.",
      "Vor dem Anruf zählt die Vorbereitung.",
      "Der nächste Schritt muss vor dem Gespräch klar sein.",
      "Vertrieb beginnt mit Zuhören.",
      "Wer vorbereitet ist, wirkt verbindlich.",
      "Prioritäten im Vertrieb heißen: Kunden, Chancen, Termine.",
      "Ein klarer Tagesplan schützt vor Aktionismus.",
      "Bedarf klären, bevor Lösungen angeboten werden.",
      "Gute Vorbereitung spart lange Nacharbeit.",
      "Der Kalender zeigt Aktivität, das CRM zeigt Substanz.",
      "Kunden erwarten Klarheit, nicht Tempo allein.",
      "Wer Kundentermine plant, plant auch Folgeaktionen.",
      "Eine gute Pipeline braucht tägliche Pflege.",
      "Heute zählt der nächste konkrete Schritt.",
      "Vertrieb ohne Struktur wird schnell beliebig.",
      "Erst die wichtigen Chancen, dann der Rest.",
      "Gesprächsziele vorher festlegen.",
      "Kundennutzen klar machen, bevor Details folgen.",
      "Wer Einwände erwartet, antwortet besser.",
      "Der beste Termin beginnt vor dem Termin.",
      "Klare Vorbereitung schafft bessere Abschlüsse.",
      "Ein Angebot beginnt nicht mit der Vorlage.",
      "Relevanz entsteht durch Verständnis.",
      "Chancen prüfen, bevor Zeit investiert wird.",
      "Kundenhistorie lesen, bevor Kontakt entsteht.",
      "Ein guter Vertriebstag braucht klare Reihenfolge.",
      "Nicht jeder Kontakt ist gleich wichtig.",
      "Fokus auf die Chancen mit nächstem Schritt.",
      "Wer vorbereitet fragt, bekommt bessere Antworten.",
      "Der Tag startet mit Pipeline-Klarheit.",
      "Gute Beratung braucht saubere Informationen.",
      "Kundengespräche brauchen Ziel, Struktur und Nacharbeit.",
      "Ein klarer Einstieg macht Gespräche leichter.",
      "Vertrieb ist planbar, wenn Schritte sichtbar sind.",
      "Wer morgens sortiert, verkauft gezielter.",
      "Angebote brauchen Entscheidungskriterien.",
      "Kundennähe beginnt mit Aufmerksamkeit.",
      "Termine ohne Ziel erzeugen wenig Fortschritt.",
      "Die beste Chance ist die mit klarem nächsten Schritt.",
      "Klarheit im Vertrieb beginnt vor dem ersten Kontakt."
    ],
    "afternoon": [
      "Nachfassen ist Teil des Verkaufs.",
      "Ein Gespräch ist erst abgeschlossen, wenn es dokumentiert ist.",
      "CRM-Pflege ist keine Nacharbeit, sondern Vertriebsarbeit.",
      "Angebote brauchen Verbindlichkeit und Frist.",
      "Der nächste Schritt gehört direkt ins System.",
      "Offene Kundenfragen heute noch klären.",
      "Was zugesagt wurde, muss nachvollziehbar sein.",
      "Nach dem Termin beginnt die Verbindlichkeit.",
      "Ein guter Status spart Rückfragen.",
      "Chancen ohne nächsten Schritt verlieren Tempo.",
      "Nachfassen, solange das Gespräch noch präsent ist.",
      "Kundenzusagen gehören nicht ins Gedächtnis.",
      "Der Nachmittag gehört den offenen Vorgängen.",
      "Angebote prüfen, bevor sie liegen bleiben.",
      "Wer sauber dokumentiert, verkauft verlässlicher.",
      "Offene Einwände gehören sichtbar gemacht.",
      "Eine Pipeline ist nur so gut wie ihre Aktualität.",
      "Kundenkontakt braucht saubere Nachbereitung.",
      "Was heute besprochen wurde, heute festhalten.",
      "Verbindlichkeit entsteht durch klare Folgeaktionen.",
      "Kein Angebot ohne nächsten Termin.",
      "Keine Chance ohne aktuelle Information.",
      "Nachfassen zeigt Professionalität.",
      "Der Tagesabschluss zeigt die Pipeline-Qualität.",
      "Wer dokumentiert, schützt die Kundenbeziehung.",
      "Offene Angebote brauchen Bewegung.",
      "Kundentermine enden mit klaren nächsten Schritten.",
      "Ein guter Vertriebler lässt keine Zusage offen.",
      "Nachbereitung entscheidet über Abschlusswahrscheinlichkeit.",
      "Was nicht im CRM steht, ist schwer steuerbar.",
      "Heute aktualisieren, morgen gezielter verkaufen.",
      "Der Kunde merkt, ob intern sauber gearbeitet wird.",
      "Verbindliche Kommunikation schafft Vertrauen.",
      "Offene Rückmeldungen nicht in den nächsten Tag schieben.",
      "Angebote werden besser, wenn Fragen geklärt sind.",
      "Der nächste Schritt ist wichtiger als der gute Eindruck.",
      "Nachfassen braucht Zeitpunkt und Anlass.",
      "Chancen bewerten, bevor sie weiterlaufen.",
      "Gute Vertriebsarbeit endet mit Klarheit.",
      "Wer nachhält, bleibt im Gespräch.",
      "Ein sauberer Abschluss spart den Neustart.",
      "Kundendaten aktuell halten, bevor sie fehlen.",
      "Offene Aufgaben sichtbar machen.",
      "Ein Angebot ohne Nachverfolgung bleibt Papier.",
      "Heute klären, was den Abschluss verzögert.",
      "Pipeline-Arbeit ist Tagesarbeit.",
      "Nach dem Gespräch zählt die Umsetzung.",
      "Verbindlichkeit muss dokumentiert sein.",
      "Der letzte Vertriebsblick gilt den offenen Zusagen.",
      "Ein guter Verkaufstag endet mit aktuellen Daten."
    ]
  },
  "employee": {
    "morning": [
      "Erst Überblick, dann Tempo.",
      "Ein klarer Start spart Rückfragen.",
      "Prioritäten zuerst, Details danach.",
      "Was heute wichtig ist, gehört früh auf den Tisch.",
      "Aufgaben sortieren, bevor Arbeit startet.",
      "Klarheit im Tagesplan reduziert Unterbrechungen.",
      "Gute Arbeit beginnt mit Vorbereitung.",
      "Wer früh abstimmt, arbeitet ruhiger.",
      "Offene Fragen besser vor dem Start klären.",
      "Ein sauberer Anfang spart Korrekturen.",
      "Der Tag braucht Reihenfolge.",
      "Erst prüfen, dann umsetzen.",
      "Was fehlt, sollte früh sichtbar werden.",
      "Abstimmung vor Aufwand.",
      "Klare Aufgaben machen Arbeit leichter.",
      "Der erste Schritt bestimmt den Ablauf.",
      "Prioritäten helfen gegen unnötige Hektik.",
      "Wer weiß, was zählt, arbeitet gezielter.",
      "Tagesziele kurz prüfen, bevor es losgeht.",
      "Gute Vorbereitung verhindert doppelte Arbeit.",
      "Unklarheiten früh ansprechen.",
      "Ein kurzer Plan spart lange Suche.",
      "Was dringend wirkt, muss nicht wichtig sein.",
      "Erst das Wichtige sichern, dann den Rest.",
      "Arbeitsmittel prüfen, bevor sie gebraucht werden.",
      "Ordnung am Anfang spart Zeit im Verlauf.",
      "Der Tag wird leichter, wenn Aufgaben klar sind.",
      "Früh klären, wer was braucht.",
      "Gute Ergebnisse brauchen klare Grundlagen.",
      "Vor dem Start die Abhängigkeiten prüfen.",
      "Wer sauber beginnt, muss weniger nacharbeiten.",
      "Aufgaben sichtbar machen, bevor Lücken entstehen.",
      "Ein klarer Tagesstart schafft Verlässlichkeit.",
      "Rückfragen vermeiden durch klare Abstimmung.",
      "Erst verstehen, dann erledigen.",
      "Der Überblick schützt vor falschem Tempo.",
      "Was offen ist, gehört nicht übersehen.",
      "Heute zählt eine klare Reihenfolge.",
      "Gute Arbeit beginnt mit dem richtigen Fokus.",
      "Der Start entscheidet über den Aufwand.",
      "Kleine Klärungen verhindern große Umwege.",
      "Früh sortieren, später schneller arbeiten.",
      "Wer priorisiert, arbeitet bewusster.",
      "Der Tagesplan muss sichtbar sein.",
      "Was nicht klar ist, kostet später Zeit.",
      "Erst die Aufgabe verstehen, dann die Lösung suchen.",
      "Klare Kommunikation spart doppelte Wege.",
      "Struktur vor Geschwindigkeit.",
      "Der Morgen gehört der Orientierung.",
      "Ein ruhiger Start braucht klare Aufgaben."
    ],
    "afternoon": [
      "Was erledigt ist, gehört dokumentiert.",
      "Offene Punkte jetzt klären, nicht morgen suchen.",
      "Ein kurzer Zwischenstand verhindert Rückfragen.",
      "Gute Arbeit endet nicht im Kopf, sondern im System.",
      "Vor Feierabend zählt, was noch offen ist.",
      "Nacharbeit ist Teil der Aufgabe.",
      "Was begonnen wurde, braucht einen sauberen Stand.",
      "Offene Fragen sichtbar machen.",
      "Übergaben brauchen klare Informationen.",
      "Dokumentation spart spätere Suche.",
      "Ein erledigter Punkt braucht klare Ablage.",
      "Nachmittags zählt der saubere Abschluss.",
      "Wer dokumentiert, hilft dem nächsten Schritt.",
      "Unklare Stände erzeugen doppelte Arbeit.",
      "Was offen bleibt, braucht eine Notiz.",
      "Ergebnisse prüfen, bevor sie weitergegeben werden.",
      "Qualität zeigt sich oft am Ende.",
      "Der Tagesabschluss beginnt vor dem letzten Moment.",
      "Rückfragen vermeiden durch saubere Übergabe.",
      "Offene Aufgaben nicht im Kopf behalten.",
      "Was heute klar ist, hilft morgen weiter.",
      "Ein kurzer Status spart lange Erklärungen.",
      "Saubere Ablage ist Teil guter Arbeit.",
      "Nachhalten verhindert Wiederholungsfehler.",
      "Fertig heißt nachvollziehbar fertig.",
      "Übergaben brauchen Kontext, nicht nur Dateien.",
      "Was fehlt, sollte heute noch sichtbar werden.",
      "Ein klarer Abschluss schützt den nächsten Start.",
      "Ergebnisse sichern, bevor der Tag endet.",
      "Offene Punkte gehören in die Planung.",
      "Dokumentieren, solange der Stand frisch ist.",
      "Nachfragen ist besser als falsch abschließen.",
      "Wer sauber abschließt, startet morgen leichter.",
      "Kleine Lücken werden später groß.",
      "Ein guter Tagesstand ist kurz und klar.",
      "Qualität braucht Prüfung, nicht Vermutung.",
      "Was weitergegeben wird, muss verständlich sein.",
      "Der letzte Schritt ist oft die Dokumentation.",
      "Offene Themen brauchen Zuständigkeit.",
      "Arbeitsstände müssen auffindbar bleiben.",
      "Heute ordnen, morgen schneller weiterarbeiten.",
      "Ein sauberer Abschluss spart neue Rückfragen.",
      "Was erledigt wurde, sollte sichtbar sein.",
      "Übergaben nicht auf den letzten Moment schieben.",
      "Der Nachmittag gehört dem Nachhalten.",
      "Gute Arbeit bleibt nachvollziehbar.",
      "Offene Punkte früh melden, statt spät retten.",
      "Was nicht festgehalten ist, bleibt unsicher.",
      "Abschlussklarheit ist Teil der Qualität.",
      "Der nächste Arbeitstag beginnt mit dem heutigen Stand."
    ]
  }
};

export function getDashboardDailyImpulse(role?: string | null, date = new Date()) {
  const audience: DailyImpulseAudience =
    role === "GESCHAEFTSFUEHRER" || role === "ADMIN" ? "management" : role === "VERTRIEB" ? "sales" : "employee";
  const period: DailyImpulsePeriod = date.getHours() >= 14 ? "afternoon" : "morning";
  const impulses = dashboardDailyImpulses[audience][period];
  const dayIndex = Math.floor(new Date(date.getFullYear(), date.getMonth(), date.getDate()).getTime() / 86_400_000);
  const impulseIndex = impulses.length > 0 ? dayIndex % impulses.length : 0;

  return {
    audience,
    audienceLabel: audience === "management" ? "Geschäftsführung" : audience === "sales" ? "Vertrieb" : "Mitarbeiter",
    period,
    periodLabel: period === "afternoon" ? "Nachmittag" : "Morgen",
    text: impulses[impulseIndex] ?? "",
  };
}
