import { Role } from "@prisma/client";
import {
  canAccessEmployeeCosts,
  canArchiveProjects,
  canConvertOnlineRequests,
  canDeleteContacts,
  canDeleteInvoices,
  canDeleteOffers,
  canDeleteTasks,
  canManageCatalogItems,
  canManageContacts,
  canManageInvoices,
  canManageOffers,
  canManagePlanningEntries,
  canManageStatusRules,
  canManageProjectTimeEntries,
  canManageProjects,
  canManageUsers,
  canSendInvoiceDocuments,
  canSendOfferDocuments,
  canReadContacts,
  canReadOnlineRequests,
} from "@/lib/permissions";
import {
  canAccessJarvisDataClass,
  JarvisAccessProfile,
  JarvisActor,
  JarvisDataClass,
} from "@/lib/jarvis/security";

export type JarvisActionRisk = "read" | "prepare" | "write" | "critical";
export type JarvisActionImplementation = "planned" | "available";
export type JarvisConfirmationLevel = "none" | "preview" | "confirm" | "critical";

export type JarvisActionDefinition = {
  id: string;
  title: string;
  category:
    | "navigation"
    | "task"
    | "planning"
    | "time"
    | "project"
    | "contact"
    | "catalog"
    | "offer"
    | "invoice"
    | "sales"
    | "document"
    | "personnel"
    | "bulk"
    | "automation";
  risk: JarvisActionRisk;
  confirmation: JarvisConfirmationLevel;
  dataClasses: JarvisDataClass[];
  implementation: JarvisActionImplementation;
  canUse: (actor: JarvisActor) => boolean;
};

export type JarvisActionDecision = {
  known: boolean;
  permitted: boolean;
  executable: boolean;
  requiresConfirmation: boolean;
  reason: "allowed" | "unknown_action" | "role" | "data_class" | "not_implemented";
  action?: JarvisActionDefinition;
};

const isActiveInternalUser = (actor: JarvisActor) => actor.role !== Role.GAST;

export const JARVIS_ACTIONS: JarvisActionDefinition[] = [
  {
    id: "navigation.open",
    title: "Bereich oder Datensatz öffnen",
    category: "navigation",
    risk: "read",
    confirmation: "none",
    dataClasses: ["internal"],
    implementation: "available",
    canUse: () => true,
  },
  {
    id: "project.read",
    title: "Projekt suchen oder zusammenfassen",
    category: "project",
    risk: "read",
    confirmation: "none",
    dataClasses: ["internal"],
    implementation: "available",
    canUse: isActiveInternalUser,
  },
  {
    id: "contact.read",
    title: "Kunde oder Kontakt suchen",
    category: "contact",
    risk: "read",
    confirmation: "none",
    dataClasses: ["customer"],
    implementation: "available",
    canUse: canReadContacts,
  },
  {
    id: "task.read",
    title: "Berechtigte Aufgabe suchen",
    category: "task",
    risk: "read",
    confirmation: "none",
    dataClasses: ["internal"],
    implementation: "available",
    canUse: isActiveInternalUser,
  },
  {
    id: "offer.read",
    title: "Angebot suchen oder zusammenfassen",
    category: "offer",
    risk: "read",
    confirmation: "none",
    dataClasses: ["customer"],
    implementation: "available",
    canUse: canManageOffers,
  },
  {
    id: "invoice.read",
    title: "Rechnung suchen oder zusammenfassen",
    category: "invoice",
    risk: "read",
    confirmation: "none",
    dataClasses: ["financial"],
    implementation: "available",
    canUse: canManageInvoices,
  },
  {
    id: "online-request.read",
    title: "Online-Anfragen lesen und zusammenfassen",
    category: "sales",
    risk: "read",
    confirmation: "none",
    dataClasses: ["customer"],
    implementation: "available",
    canUse: canReadOnlineRequests,
  },
  {
    id: "winter-calculation.prepare",
    title: "Winterdienst kalkulieren",
    category: "catalog",
    risk: "prepare",
    confirmation: "preview",
    dataClasses: ["internal"],
    implementation: "available",
    canUse: isActiveInternalUser,
  },
  {
    id: "winter-calculation.save",
    title: "Winterdienst-Kalkulation speichern",
    category: "catalog",
    risk: "write",
    confirmation: "confirm",
    dataClasses: ["internal", "customer"],
    implementation: "available",
    canUse: canManageProjects,
  },
  {
    id: "vehicle-trip-calculation.prepare",
    title: "Fahrt und Fahrzeugkosten kalkulieren",
    category: "catalog",
    risk: "prepare",
    confirmation: "preview",
    dataClasses: ["internal"],
    implementation: "available",
    canUse: isActiveInternalUser,
  },
  {
    id: "vehicle-trip-calculation.save",
    title: "Fahrtenkalkulation speichern",
    category: "catalog",
    risk: "write",
    confirmation: "confirm",
    dataClasses: ["internal"],
    implementation: "available",
    canUse: canManageProjects,
  },
  {
    id: "sales.analysis.read",
    title: "Vertriebs- und Projektchancen im Dry-Run analysieren",
    category: "sales",
    risk: "read",
    confirmation: "none",
    dataClasses: ["customer", "financial"],
    implementation: "available",
    canUse: (actor) => actor.role === Role.GESCHAEFTSFUEHRER,
  },
  {
    id: "management.service-rate-analysis.read",
    title: "Leistungen und Stundenverrechnungssätze analysieren",
    category: "catalog",
    risk: "read",
    confirmation: "none",
    dataClasses: ["financial"],
    implementation: "available",
    canUse: canManageInvoices,
  },
  {
    id: "management.material-analysis.read",
    title: "Materialien, Artikelpreise und Lagerabweichungen analysieren",
    category: "catalog",
    risk: "read",
    confirmation: "none",
    dataClasses: ["financial"],
    implementation: "available",
    canUse: canManageInvoices,
  },
  {
    id: "task.prepare",
    title: "Aufgabe vorbereiten",
    category: "task",
    risk: "prepare",
    confirmation: "preview",
    dataClasses: ["internal"],
    implementation: "available",
    canUse: isActiveInternalUser,
  },
  {
    id: "task.create",
    title: "Aufgabe anlegen",
    category: "task",
    risk: "write",
    confirmation: "confirm",
    dataClasses: ["internal"],
    implementation: "available",
    canUse: isActiveInternalUser,
  },
  {
    id: "task-comment.prepare",
    title: "Aufgabenkommentar vorbereiten",
    category: "task",
    risk: "prepare",
    confirmation: "preview",
    dataClasses: ["internal"],
    implementation: "available",
    canUse: isActiveInternalUser,
  },
  {
    id: "task-comment.create",
    title: "Aufgabenkommentar speichern",
    category: "task",
    risk: "write",
    confirmation: "confirm",
    dataClasses: ["internal"],
    implementation: "available",
    canUse: isActiveInternalUser,
  },
  {
    id: "task.delete",
    title: "Aufgabe kontrolliert archivieren oder wiederherstellen",
    category: "task",
    risk: "critical",
    confirmation: "critical",
    dataClasses: ["internal"],
    implementation: "available",
    canUse: canDeleteTasks,
  },
  {
    id: "planning.prepare",
    title: "Termin oder Terminwunsch vorbereiten",
    category: "planning",
    risk: "prepare",
    confirmation: "preview",
    dataClasses: ["internal"],
    implementation: "available",
    canUse: isActiveInternalUser,
  },
  {
    id: "planning.create",
    title: "Termin oder Terminwunsch speichern",
    category: "planning",
    risk: "write",
    confirmation: "confirm",
    dataClasses: ["internal"],
    implementation: "available",
    canUse: isActiveInternalUser,
  },
  {
    id: "planning.move",
    title: "Termin kontrolliert verschieben",
    category: "planning",
    risk: "critical",
    confirmation: "critical",
    dataClasses: ["internal"],
    implementation: "available",
    canUse: canManagePlanningEntries,
  },
  {
    id: "project-logbook.prepare",
    title: "Projektlogbuch-Eintrag vorbereiten",
    category: "project",
    risk: "prepare",
    confirmation: "preview",
    dataClasses: ["internal"],
    implementation: "available",
    canUse: isActiveInternalUser,
  },
  {
    id: "project-logbook.create",
    title: "Projektlogbuch-Eintrag speichern",
    category: "project",
    risk: "write",
    confirmation: "confirm",
    dataClasses: ["internal"],
    implementation: "available",
    canUse: isActiveInternalUser,
  },
  {
    id: "time.prepare",
    title: "Zeiteintrag vorbereiten",
    category: "time",
    risk: "prepare",
    confirmation: "preview",
    dataClasses: ["internal"],
    implementation: "available",
    canUse: isActiveInternalUser,
  },
  {
    id: "time.create",
    title: "Eigenen manuellen Zeiteintrag speichern",
    category: "time",
    risk: "write",
    confirmation: "confirm",
    dataClasses: ["internal"],
    implementation: "available",
    canUse: isActiveInternalUser,
  },
  {
    id: "time.manage",
    title: "Zeiteintrag für andere verwalten",
    category: "time",
    risk: "write",
    confirmation: "confirm",
    dataClasses: ["internal"],
    implementation: "available",
    canUse: canManageProjectTimeEntries,
  },
  {
    id: "time.session.manage",
    title: "Eigene laufende Stempelung bedienen",
    category: "time",
    risk: "critical",
    confirmation: "critical",
    dataClasses: ["internal"],
    implementation: "available",
    canUse: isActiveInternalUser,
  },
  {
    id: "project.status.change",
    title: "Projektstatus kontrolliert ändern",
    category: "project",
    risk: "critical",
    confirmation: "critical",
    dataClasses: ["customer"],
    implementation: "available",
    canUse: canManageProjects,
  },
  {
    id: "project.manage",
    title: "Projektstammdaten kontrolliert bearbeiten",
    category: "project",
    risk: "write",
    confirmation: "confirm",
    dataClasses: ["customer"],
    implementation: "available",
    canUse: canManageProjects,
  },
  {
    id: "project.archive",
    title: "Projekt archivieren oder wiederherstellen",
    category: "project",
    risk: "critical",
    confirmation: "critical",
    dataClasses: ["customer"],
    implementation: "available",
    canUse: canArchiveProjects,
  },
  {
    id: "online-request.convert",
    title: "Online-Anfrage kontrolliert in ein Projekt umwandeln",
    category: "project",
    risk: "critical",
    confirmation: "critical",
    dataClasses: ["customer"],
    implementation: "available",
    canUse: canConvertOnlineRequests,
  },
  {
    id: "contact.manage",
    title: "Kontakt anlegen oder bearbeiten",
    category: "contact",
    risk: "write",
    confirmation: "confirm",
    dataClasses: ["customer"],
    implementation: "available",
    canUse: canManageContacts,
  },
  {
    id: "contact.delete",
    title: "Kontakt löschen",
    category: "contact",
    risk: "critical",
    confirmation: "critical",
    dataClasses: ["customer"],
    implementation: "available",
    canUse: canDeleteContacts,
  },
  {
    id: "offer.prepare",
    title: "Angebot oder Nachtrag vorbereiten",
    category: "offer",
    risk: "prepare",
    confirmation: "preview",
    dataClasses: ["customer"],
    implementation: "available",
    canUse: canManageOffers,
  },
  {
    id: "offer.draft.create",
    title: "Angebots- oder Nachtragsentwurf speichern",
    category: "offer",
    risk: "write",
    confirmation: "confirm",
    dataClasses: ["customer"],
    implementation: "available",
    canUse: canManageOffers,
  },
  {
    id: "offer.finalize",
    title: "Angebotsentwurf finalisieren",
    category: "offer",
    risk: "critical",
    confirmation: "critical",
    dataClasses: ["customer"],
    implementation: "available",
    canUse: canManageOffers,
  },
  {
    id: "offer.send",
    title: "Finalisiertes Angebot kontrolliert versenden",
    category: "offer",
    risk: "critical",
    confirmation: "critical",
    dataClasses: ["customer"],
    implementation: "available",
    canUse: canSendOfferDocuments,
  },
  {
    id: "offer.manage",
    title: "Angebotsstatus Gewonnen oder Verloren ändern",
    category: "offer",
    risk: "critical",
    confirmation: "critical",
    dataClasses: ["customer"],
    implementation: "available",
    canUse: canManageOffers,
  },
  {
    id: "offer.delete",
    title: "Angebot kontrolliert löschen oder wiederherstellen",
    category: "offer",
    risk: "critical",
    confirmation: "critical",
    dataClasses: ["customer"],
    implementation: "available",
    canUse: canDeleteOffers,
  },
  {
    id: "invoice.prepare",
    title: "Rechnungsentwurf mit Fakturavorprüfung vorbereiten",
    category: "invoice",
    risk: "prepare",
    confirmation: "preview",
    dataClasses: ["financial"],
    implementation: "available",
    canUse: canManageInvoices,
  },
  {
    id: "invoice.finalize",
    title: "Rechnung fakturieren",
    category: "invoice",
    risk: "critical",
    confirmation: "critical",
    dataClasses: ["financial"],
    implementation: "available",
    canUse: canManageInvoices,
  },
  {
    id: "invoice.mark-paid",
    title: "Zahlungseingang vollständig bestätigen",
    category: "invoice",
    risk: "critical",
    confirmation: "critical",
    dataClasses: ["financial"],
    implementation: "available",
    canUse: canManageInvoices,
  },
  {
    id: "invoice.remind",
    title: "Mahnung kontrolliert erzeugen",
    category: "invoice",
    risk: "critical",
    confirmation: "critical",
    dataClasses: ["financial", "customer"],
    implementation: "available",
    canUse: canManageInvoices,
  },
  {
    id: "invoice.cancel",
    title: "Rechnung stornieren",
    category: "invoice",
    risk: "critical",
    confirmation: "critical",
    dataClasses: ["financial"],
    implementation: "available",
    canUse: canManageInvoices,
  },
  {
    id: "invoice.credit",
    title: "Teilgutschrift oder Rechnungskorrektur erstellen",
    category: "invoice",
    risk: "critical",
    confirmation: "critical",
    dataClasses: ["financial"],
    implementation: "available",
    canUse: canManageInvoices,
  },
  {
    id: "invoice.delete",
    title: "Rechnungsentwurf kontrolliert löschen oder wiederherstellen",
    category: "invoice",
    risk: "critical",
    confirmation: "critical",
    dataClasses: ["financial"],
    implementation: "available",
    canUse: canDeleteInvoices,
  },
  {
    id: "document.send",
    title: "Fakturierte Rechnung kontrolliert versenden",
    category: "invoice",
    risk: "critical",
    confirmation: "critical",
    dataClasses: ["customer"],
    implementation: "available",
    canUse: canSendInvoiceDocuments,
  },
  {
    id: "catalog.manage",
    title: "Artikel, Leistung oder Paket verwalten",
    category: "catalog",
    risk: "write",
    confirmation: "confirm",
    dataClasses: ["internal"],
    implementation: "available",
    canUse: canManageCatalogItems,
  },
  {
    id: "personnel.read",
    title: "Mitarbeiterstammdaten rollengerecht zusammenfassen",
    category: "personnel",
    risk: "read",
    confirmation: "none",
    dataClasses: ["personnel"],
    implementation: "available",
    canUse: canManageUsers,
  },
  {
    id: "personnel.manage",
    title: "Personalstammdaten oder Rolle ändern",
    category: "personnel",
    risk: "critical",
    confirmation: "critical",
    dataClasses: ["personnel"],
    implementation: "available",
    canUse: canManageUsers,
  },
  {
    id: "payroll.manage",
    title: "Lohn- oder Mitarbeiterkostendaten ändern",
    category: "personnel",
    risk: "critical",
    confirmation: "critical",
    dataClasses: ["payroll"],
    implementation: "available",
    canUse: (actor) => canManageUsers(actor) && canAccessEmployeeCosts(actor),
  },
  {
    id: "bulk.update",
    title: "Massenänderung ausführen",
    category: "bulk",
    risk: "critical",
    confirmation: "critical",
    dataClasses: ["internal"],
    implementation: "available",
    canUse: (actor) => canManageUsers(actor) && canManageContacts(actor),
  },
  {
    id: "automation.read",
    title: "Automationsstatus und Dry-Run lesen",
    category: "automation",
    risk: "read",
    confirmation: "none",
    dataClasses: ["internal"],
    implementation: "available",
    canUse: canManageStatusRules,
  },
  {
    id: "automation.manage",
    title: "Automation konfigurieren oder ausführen",
    category: "automation",
    risk: "critical",
    confirmation: "critical",
    dataClasses: ["internal"],
    implementation: "available",
    canUse: canManageStatusRules,
  },
];

function bothActorsPass(profile: JarvisAccessProfile, predicate: (actor: JarvisActor) => boolean) {
  return predicate(profile.sessionActor) && predicate(profile.effectiveActor);
}

export function getJarvisActionDecision(
  actionId: string,
  profile: JarvisAccessProfile
): JarvisActionDecision {
  const action = JARVIS_ACTIONS.find((candidate) => candidate.id === actionId);
  if (!action) {
    return {
      known: false,
      permitted: false,
      executable: false,
      requiresConfirmation: false,
      reason: "unknown_action",
    };
  }

  if (!action.dataClasses.every((dataClass) => canAccessJarvisDataClass(profile, dataClass))) {
    return {
      known: true,
      permitted: false,
      executable: false,
      requiresConfirmation: action.confirmation !== "none",
      reason: "data_class",
      action,
    };
  }

  if (!bothActorsPass(profile, action.canUse)) {
    return {
      known: true,
      permitted: false,
      executable: false,
      requiresConfirmation: action.confirmation !== "none",
      reason: "role",
      action,
    };
  }

  return {
    known: true,
    permitted: true,
    executable: action.implementation === "available",
    requiresConfirmation: action.confirmation !== "none",
    reason: action.implementation === "available" ? "allowed" : "not_implemented",
    action,
  };
}

export function getJarvisActionCatalog(profile: JarvisAccessProfile) {
  return JARVIS_ACTIONS.map((action) => getJarvisActionDecision(action.id, profile));
}
