ALTER TABLE "CatalogItem"
ADD COLUMN IF NOT EXISTS "salesPriceCalculationMode" TEXT NOT NULL DEFAULT 'manual',
ADD COLUMN IF NOT EXISTS "salesRatePerHour" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "scheduledSalesRatePerHour" DOUBLE PRECISION;

